apiVersion: batch/v1
kind: CronJob
metadata:
  name: send-batch-label-studio
spec:
  schedule: "*/30 * * * *" # toutes les 30 minutes, si on veut faire toutes les minutes : "* * * * *"
  concurrencyPolicy: Forbid # ensure only one pod is running at a time
  jobTemplate:
    spec:
      backoffLimit: 0  # Number of retries before considering the Job as failed
      template:
        spec:
          containers:
          - name: send-batch-label-studio
            image: inseefrlab/onyxia-python-datascience:py3.10.9
            imagePullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - |
                cd /tmp &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/requirements.txt &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/instructions.txt &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/taxonomy.xml &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/var_index_mapping/correspondance_intitule_nature_activite.json &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/var_index_mapping/correspondance_intitule_cj.json &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/validate_xml.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/display_last_pk.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/display_current_target_folder_id.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/display_last_target_folder_id.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/get_last_target_folder_id.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/count_project_id.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/update_create_project.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/s3_sync_source.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/s3_create_target.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/s3_sync_target.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/transform_to_json.py &&
                wget https://github.com/InseeFrLab/codif-ape-annotation/raw/main/data/data_naf.xlsx &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/generate_templates/create_template_NAF2025_AGRI.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/generate_templates/create_template_NAF2025_CG.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/generate_templates/create_template_NAF2025_PSA.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/generate_templates/create_template_NAF2025_SOCET.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/generate_templates/create_template_NAF2025_SSP.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/nace-rev-2-1/batch_AGRI.sh &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/nace-rev-2-1/batch_CG.sh &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/nace-rev-2-1/batch_PSA.sh &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/nace-rev-2-1/batch_SOCET.sh &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/nace-rev-2-1/batch_SSP.sh &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/labeling_pipeline_s3.sh &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-annotation/main/utils/nace-rev-2-1/launch_labeling.sh &&
                chmod +x labeling_pipeline_s3.sh &&
                chmod +x batch_AGRI.sh &&
                chmod +x batch_CG.sh &&
                chmod +x batch_PSA.sh &&
                chmod +x batch_SOCET.sh &&
                chmod +x batch_SSP.sh &&
                chmod +x launch_labeling.sh &&
                export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT &&
                ./launch_labeling.sh 
            volumeMounts:
            - name: tmp
              mountPath: "/tmp"
            envFrom:
            # from configmap
            - configMapRef:
                    name: configmap-label-studio
            env:
            # from secrets
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-creds-service-account
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-creds-service-account
                  key: secretKey
            - name: LABEL_STUDIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-label-studio-token
                  key: token
            - name: LABEL_STUDIO_TOKEN_REV_NAF2025_AGRI
              valueFrom:
                secretKeyRef:
                  name: secret-label-studio-token-rev-naf2025-agri
                  key: token
            - name: LABEL_STUDIO_TOKEN_REV_NAF2025_CG
              valueFrom:
                secretKeyRef:
                  name: secret-label-studio-token-rev-naf2025-cg
                  key: token
            - name: LABEL_STUDIO_TOKEN_REV_NAF2025_PSA
              valueFrom:
                secretKeyRef:
                  name: secret-label-studio-token-rev-naf2025-psa
                  key: token
            - name: LABEL_STUDIO_TOKEN_REV_NAF2025_SOCET
              valueFrom:
                secretKeyRef:
                  name: secret-label-studio-token-rev-naf2025-socet
                  key: token
            - name: LABEL_STUDIO_TOKEN_REV_NAF2025_SSP
              valueFrom:
                secretKeyRef:
                  name: secret-label-studio-token-rev-naf2025-ssp
                  key: token
          restartPolicy: Never
          serviceAccountName: send-batch-label-studio
          volumes:
          - name: tmp
            emptyDir: {}
