apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: send-batch-label-studio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: send-batch-label-studio
  namespace: user-nrandriamanana
