apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: label-studio
spec:
  project: default
  source:
    repoURL: https://github.com/TheAIWizard/codif-ape-cd.git
    targetRevision: main
    path: etl-label-studio
  destination:
    server: https://kubernetes.default.svc
    namespace: projet-ape
  syncPolicy:
    automated:
      selfHeal: true
