apiVersion: batch/v1
kind: CronJob
metadata:
  name: etl-sampling
spec:
  timeZone: "Europe/Paris"
  schedule: "20 10 * * 1"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl-sampling
            image: inseefrlab/onyxia-python-datascience:py3.10.9
            imagePullPolicy: IfNotPresent
            command:
              - /bin/sh
              - -c
              - | 
                export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT &&
                cd /tmp &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-API/main/requirements.txt &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-API/main/utils/extract_db.py &&
                wget https://raw.githubusercontent.com/InseeFrLab/codif-ape-API/main/utils/extract_db.sh &&
                chmod +x extract_db.sh &&
                ./extract_db.sh
            volumeMounts:
              - name: tmp
                mountPath: "/tmp"
            envFrom:
              - configMapRef:
                  name: configmap-etl-sampling
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: secretKey
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-api-creds
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-api-creds
                  key: password
          restartPolicy: Never
          serviceAccountName: etl-sampling
          volumes:
          - name: tmp
            emptyDir: {}
